export const INCREASE_SCORE = "INCREASE_SCORE";
export const DECREASE_SCORE = "DECREASE_SCORE";
export const SET_GAME_RESULT = "SET_GAME_RESULT";
export const RESET_GAME_RESULT = "RESET_GAME_RESULT";
export const SET_USER_CHOICE = "SET_USER_CHOICE";
export const SET_COMPUTER_CHOICE = 'SET_COMPUTER_CHOICE';